### PR TITLE
Cleanup reorganized

### PR DESCRIPTION
**Pull request by fbudin69500**
@cdeepakroy Could you let me know what you think of this reorganization of the code? I saw that in the meantime you added some modifications to pyLAR that will need to be manually integrated in this branch, but it should not be too difficult.

### CODE REVIEW

**Comment by fbudin69500** [comment]
@cdeepakroy Could you review my changes? I have changed a lot of things in the organization of the code, but I have integrated in this branch the changes I saw you made after I started working on my branch.

**Comment by cdeepakroy** [comment]
@fbudin69500 LGTM! I like the new organization.

**Comment by fbudin69500** [comment]
@cdeepakroy Thanks for the review.

**Comment by fbudin69500** [comment]
@cdeepakroy . I have corrected the conflicts. Maybe we could merge after your code review, and move on to create a separate repository for alm later?

**Pull request merged**
